### ISSUE TITLE
external elementtree breaking other packages

### ISSUE THREAD

**Issue by dougalsutherland** [SublimeText/LaTeXTools#821]
It seems that the presence of `external/elementtree/ElementTree.py` is breaking SublimeCodeIntel for me:

```
+ Info: processing `Python': please wait...
Exception in thread scanning thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 802, in _codeintel_scan
    mgr = codeintel_manager()
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 762, in codeintel_manager
    db_import_everything_langs=None,
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 139, in __init__
    self._register_modules(extra_module_dirs)
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 197, in _register_modules
    self._register_module(module_path)
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/manager.py", line 279, in _register_module
    module = imp.load_module(module_name, *iinfo)
  File "./python3.3/imp.py", line 180, in load_module
  File "./python3.3/imp.py", line 119, in load_source
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_html.py", line 50, in <module>
    from codeintel2.lang_xml import XMLLangIntel
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/codeintel2/lang_xml.py", line 54, in <module>
    import koXMLTreeService
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/koXMLTreeService.py", line 488, in <module>
    import HTMLTreeParser
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/libs/HTMLTreeParser.py", line 43, in <module>
    from elementtree import ElementTree
  File "/Users/dougal/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/external/elementtree/ElementTree.py", line 836, in <module>
    def _escape_cdata(text, encoding=None, replace=string.replace):
AttributeError: 'module' object has no attribute 'replace'
```

The problem is that SublimeCodeIntel is importing from `elementtree`, and the version in LaTeXTools's external lib is not python 3 compatible. I haven't checked, but this was *probably* broken by https://github.com/SublimeText/LaTeXTools/commit/b9b86ebd60825c2aca30221fe9e3eaf77fce9d86: the old way of putting things on the path cleaned it up afterwards, but this one doesn't.

This could probably be fixed by adding say `03_remove_external_libs_from_path.py` with content:

    import os
    import sys

    external_dir = os.path.abspath(os.path.join(__dir__, 'external'))
    sys.path = [p for p in sys.path if os.path.abspath(p) != external_dir]

but I'm not totally sure about how things work in Sublime plugins / if it's actually needed for any imports later in the package.

**Comment by ig0774** [comment]
Thanks for the really clear report! I'll have a fix in shortly.

**Comment by ig0774** [comment]
This should be fixed in v3.10.11, which will be available via PackageControl shortly. However, it will require restarting ST to straighten things out.

**Comment by dougalsutherland** [comment]
This works for me after upgrade and restart. Thanks for the quick fix!
