### ISSUE TITLE
Inverse search not working with Evince on Arch Linux after update to v4.4.1

### ISSUE THREAD

**Issue by xiapanqiu** [SublimeText/LaTeXTools#1636]
I am using Arch Linux, Sublime Text, and Evince. After updating LaTeXTools to version v4.4.1, inverse search no longer works.

Additionally, I would like to request support for GNOME Papers as a PDF viewer.

**Comment by deathaxe** [comment]
See also #1635.

**Comment by deathaxe** [comment]
Evince should be fixed by [v4.4.2](https://github.com/SublimeText/LaTeXTools/releases/tag/st4-4.4.2).

**Comment by xiapanqiu** [comment]
Thank @deathaxe. However, the issue persists on my end. Below is my console output. I hope it is helpful.

```
63411
Traceback (most recent call last):
  File "/home/xxx/.cache/sublime-text/Cache/LaTeXTools/viewer/evince/backward_search", line 150, in <module>
    if __spec__.name == '__main__':
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/xxx/.cache/sublime-text/Cache/LaTeXTools/viewer/evince/forward_search", line 29, in <module>
    if __spec__.name == '__main__':
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
Killing 63411
/home/xxx/.cache/sublime-text/Cache/LaTeXTools/viewer/evince/sync: line 33: kill: (63411) - No such process
```

**Comment by deathaxe** [comment]
This was one reason for it not working in 4.4.1 as a result of wrong assumptions on how modern python handles main entry points.

Those scripts are fixed and should be replaced after update to v4.4.2.

**Comment by xiapanqiu** [comment]
Yes, yes. Previously I assumed I had already updated to the new version, but I hadn’t. It is working now. Thank you so much!
